### PR TITLE
Expose formatted action results for custom formats

### PR DESCRIPTION
**Pull request by exalted**
I needed this, because [you know] sometimes you need more than what's already included :wink:

### CODE REVIEW

**Comment by exalted** [comment]
@khalidabuhakmeh any plans releasing this on NuGet please?

**Comment by khalidabuhakmeh** [comment]
Sorry I'm on vacation this week, but yes I will as soon as I get back.

**Comment by exalted** [comment]
👍

--
Ali




On Fri, May 27, 2016 at 10:03 AM -0700, "Khalid Abuhakmeh" <notifications@github.com> wrote:












Sorry I'm on vacation this week, but yes I will as soon as I get back.

**Comment by khalidabuhakmeh** [comment]
Pushed latest version `1.6.0` to nuget. Please try it out.

**Comment by exalted** [comment]
:star2: thanks

**Pull request merged**
